[project]
name = "django-exercises"
version = "0.7.0"
description = "This repository contains different examples implemented with django. Designed to help aspirants who want to step into django."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.14",
    "django-environ>=0.13.0",
    "djangorestframework>=3.17.1",
    "drf-spectacular>=0.30.0",
    "httpx>=0.28.1",
    "psycopg>=3.3.4",
    "ruff>=0.15.15",
]
